### ISSUE TITLE
unable to resolve dependency tree

### ISSUE THREAD

**Issue by audetto** [ag-grid/ag-grid-react-example#70]
On a fresh clone using

npm 8.19.3
node v18.13.0
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: ag-grid-react-example@29.0.0
npm ERR! Found: react@18.0.0
npm ERR! node_modules/react
npm ERR!   react@"18.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8.3 || ^17" from react-redux@7.2.6
npm ERR! node_modules/react-redux
npm ERR!   react-redux@"7.2.6" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

**Comment by semihozbir1** [comment]
Please try with 'yarn install'

**Comment by curiousercreative** [comment]
> Please try with 'yarn install'

That worked for me, perhaps the README should be updated if yarn should be used.

**Comment by curiousercreative** [comment]
Perhaps related, I also receive errors when trying to run the examples (Pop!_OS 22.04).

```bash
npm run examples

> ag-grid-react-example@29.3.0 examples
> webpack-dev-server --content-base src-examples/ --config config/webpack.config.examples.js --mode development --open

ℹ ｢wds｣: Project is running at http://localhost:8080/
ℹ ｢wds｣: webpack output is served from /
ℹ ｢wds｣: Content not from webpack is served from /home/curiouser/Sites/tmp/src-examples
ℹ ｢wds｣: 404s will fallback to /index.html
node:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/home/curiouser/Sites/tmp/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/curiouser/Sites/tmp/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/home/curiouser/Sites/tmp/node_modules/webpack/lib/NormalModule.js:471:10)
    at /home/curiouser/Sites/tmp/node_modules/webpack/lib/NormalModule.js:503:5
    at /home/curiouser/Sites/tmp/node_modules/webpack/lib/NormalModule.js:358:12
    at /home/curiouser/Sites/tmp/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/home/curiouser/Sites/tmp/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at Array.<anonymous> (/home/curiouser/Sites/tmp/node_modules/loader-runner/lib/LoaderRunner.js:205:4) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.16.0
```

I'm using nvm, so the simple workaround is to simple `nvm use 16` to run the examples:
```bash
nvm use 16

npm run examples
```

**Comment by semihozbir1** [comment]
Please try with 'yarn run examples' 😊

**Comment by curiousercreative** [comment]
> Please try with 'yarn run examples' blush

Not quite as simple this time :p

**Comment by Ofer-Gal** [comment]
I am running in PowerShell. Does it matter? 
yarn run examples first errors with `'NODE_OPTIONS' is not recognized as an internal or external command,
operable program or batch file.`
so I removed NODE_OPTIONS=--openssl-legacy-provider 
but then it errors with```
 'webpack-dev-server' is not recognized as an internal or external command,
operable program or batch file.
```
